### PR TITLE
[20176] Bump version to v2.13.1

### PR DESCRIPTION
**Pull request by MiguelCompany**
This PR bumps the project version to 2.13.1

### CODE REVIEW

**Review by cferreiragonz — DISMISSED** [review]

**Review by JesusPoderoso — CHANGES_REQUESTED** [review]
Fast CDR version should be updated to `v2.1.3` in both shapes-demo-ros2.repos and shapes-demo.repos files.

**Comment by Mario-DL** [comment]
> Fast CDR version should be updated to `v2.1.3` in both shapes-demo-ros2.repos and shapes-demo.repos files.

Being a patch release, I dont think we should update the dependencies

**Comment by JesusPoderoso** [comment]
> Being a patch release, I dont think we should update the dependencies

This case is an exception in my opinion, as the cmake minimum required version has been downgraded in ShapesDemo and Fast CDR.

**Review by JesusPoderoso — APPROVED** [review]
LGTM

**Pull request merged**
